name: Wrye Bash CI

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout commit
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools wheel
        python -m pip install -r requirements.txt
    - name: Test Wrye Bash
      run: |
        python -m pytest
    - name: Build Wrye Bash
      # Note the configs - needed for build.py
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "github-action@users.noreply.github.com"
        python scripts/build.py --verbose
    - name: Copy executable/license files
      run: |
        cp "scripts/build/standalone/dist/Wrye Bash.exe" Mopy
        cp LICENSE.md Mopy/LICENSE.md
#    - name: Create Apps folder # does not work
#      run: mkdir Mopy/Apps
    - name: Upload Standalone Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ format('Wrye Bash CI {0}.{1}', github.ref_name, github.sha) }}
        path: |
          Mopy/*
          Mopy/LICENSE.md
          !Mopy/**.py
          !Mopy/**.pyw
          !Mopy/**.pyd
          !Mopy/**.bat
          !Mopy/**.template
          !Mopy/redist
          !Mopy/__pycache__
          !Mopy/bash/**.py
          !Mopy/bash/__pycache__
          !Mopy/bash/basher
          !Mopy/bash/bosh
          !Mopy/bash/brec
          !Mopy/bash/env
          !Mopy/bash/game
          !Mopy/bash/gui
          !Mopy/bash/patcher
          !Mopy/bash/tests
